In [1]:
import matplotlib.pyplot as plt

import pandas as pd

In [3]:
data = {
    "Name": ["Aman", "Riya", "Kunal", "Neha", "Arjun", "Pooja"],
    "Age": [22, 25, 24, 28, 26, 23],
    "Experience": [1, 3, 2, 5, 4, 1],
    "Salary": [30000, 50000, 42000, 70000, 65000, 32000],
    "Department": ["IT", "HR", "IT", "Finance", "IT", "HR"],
    "City": ["Delhi", "Mumbai", "Delhi", "Bangalore", "Bangalore", "Mumbai"]
}

df= pd.DataFrame(data)
df

    Name  Age  Experience  Salary Department       City
0   Aman   22           1   30000         IT      Delhi
1   Riya   25           3   50000         HR     Mumbai
2  Kunal   24           2   42000         IT      Delhi
3   Neha   28           5   70000    Finance  Bangalore
4  Arjun   26           4   65000         IT  Bangalore
5  Pooja   23           1   32000         HR     Mumbai

In [4]:
df.loc["Aman":"Neha"]

Empty DataFrame
Columns: [Name, Age, Experience, Salary, Department, City]
Index: []

In [7]:
a=df.drop("Age",axis=1)
a

    Name  Experience  Salary Department       City
0   Aman           1   30000         IT      Delhi
1   Riya           3   50000         HR     Mumbai
2  Kunal           2   42000         IT      Delhi
3   Neha           5   70000    Finance  Bangalore
4  Arjun           4   65000         IT  Bangalore
5  Pooja           1   32000         HR     Mumbai

In [8]:
df

    Name  Age  Experience  Salary Department       City
0   Aman   22           1   30000         IT      Delhi
1   Riya   25           3   50000         HR     Mumbai
2  Kunal   24           2   42000         IT      Delhi
3   Neha   28           5   70000    Finance  Bangalore
4  Arjun   26           4   65000         IT  Bangalore
5  Pooja   23           1   32000         HR     Mumbai

In [9]:
df.describe()

             Age  Experience        Salary
count   6.000000    6.000000      6.000000
mean   24.666667    2.666667  48166.666667
std     2.160247    1.632993  16690.316554
min    22.000000    1.000000  30000.000000
25%    23.250000    1.250000  34500.000000
50%    24.500000    2.500000  46000.000000
75%    25.750000    3.750000  61250.000000
max    28.000000    5.000000  70000.000000

In [11]:
# broadcastin


df["Salary"]= df["Salary"]+500
df

    Name  Age  Experience  Salary Department       City
0   Aman   22           1   31000         IT      Delhi
1   Riya   25           3   51000         HR     Mumbai
2  Kunal   24           2   43000         IT      Delhi
3   Neha   28           5   71000    Finance  Bangalore
4  Arjun   26           4   66000         IT  Bangalore
5  Pooja   23           1   33000         HR     Mumbai

In [12]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Aman", "Riya", "Kunal", "Neha", "Arjun", "Pooja"],
    "Age": [22, np.nan, 24, 28, np.nan, 23],
    "Experience": [1, 3, np.nan, 5, 4, np.nan],
    "Salary": [30000, 50000, 42000, np.nan, 65000, 32000],
    "Department": ["IT", "HR", "IT", np.nan, "IT", "HR"],
    "City": ["Delhi", "Mumbai", np.nan, "Bangalore", "Bangalore", np.nan]
}

df = pd.DataFrame(data)
print(df)

    Name   Age  Experience   Salary Department       City
0   Aman  22.0         1.0  30000.0         IT      Delhi
1   Riya   NaN         3.0  50000.0         HR     Mumbai
2  Kunal  24.0         NaN  42000.0         IT        NaN
3   Neha  28.0         5.0      NaN        NaN  Bangalore
4  Arjun   NaN         4.0  65000.0         IT  Bangalore
5  Pooja  23.0         NaN  32000.0         HR        NaN

In [13]:
df["City"].unique()

array(['Delhi', 'Mumbai', nan, 'Bangalore'], dtype=object)

In [14]:
df["new sal"]= df["Salary"]*20
df

    Name   Age  Experience   Salary Department       City    new sal
0   Aman  22.0         1.0  30000.0         IT      Delhi   600000.0
1   Riya   NaN         3.0  50000.0         HR     Mumbai  1000000.0
2  Kunal  24.0         NaN  42000.0         IT        NaN   840000.0
3   Neha  28.0         5.0      NaN        NaN  Bangalore        NaN
4  Arjun   NaN         4.0  65000.0         IT  Bangalore  1300000.0
5  Pooja  23.0         NaN  32000.0         HR        NaN   640000.0

In [15]:
df["Salary"].isnull()

0    False
1    False
2    False
3     True
4    False
5    False
Name: Salary, dtype: bool

In [16]:
df.dropna()

   Name   Age  Experience   Salary Department   City   new sal
0  Aman  22.0         1.0  30000.0         IT  Delhi  600000.0

In [18]:
df["Age"].fillna(df["Age"].mean(),inplace=True)
df

C:\Users\najaf\AppData\Local\Temp\ipykernel_1748\2079956988.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(),inplace=True)

    Name    Age  Experience   Salary Department       City    new sal
0   Aman  22.00         1.0  30000.0         IT      Delhi   600000.0
1   Riya  24.25         3.0  50000.0         HR     Mumbai  1000000.0
2  Kunal  24.00         NaN  42000.0         IT        NaN   840000.0
3   Neha  28.00         5.0      NaN        NaN  Bangalore        NaN
4  Arjun  24.25         4.0  65000.0         IT  Bangalore  1300000.0
5  Pooja  23.00         NaN  32000.0         HR        NaN   640000.0

In [20]:
df["Salary"].fillna(df["Salary"].median(),inplace=True)
df

C:\Users\najaf\AppData\Local\Temp\ipykernel_1748\1603453946.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Salary"].fillna(df["Salary"].median(),inplace=True)

    Name    Age  Experience   Salary Department       City    new sal
0   Aman  22.00         1.0  30000.0         IT      Delhi   600000.0
1   Riya  24.25         3.0  50000.0         HR     Mumbai  1000000.0
2  Kunal  24.00         NaN  42000.0         IT        NaN   840000.0
3   Neha  28.00         5.0  42000.0        NaN  Bangalore        NaN
4  Arjun  24.25         4.0  65000.0         IT  Bangalore  1300000.0
5  Pooja  23.00         NaN  32000.0         HR        NaN   640000.0

In [22]:
df["Department"].fillna(df["Department"].mode()[0],inplace=True)
df

    Name    Age  Experience   Salary Department       City    new sal
0   Aman  22.00         1.0  30000.0         IT      Delhi   600000.0
1   Riya  24.25         3.0  50000.0         HR     Mumbai  1000000.0
2  Kunal  24.00         NaN  42000.0         IT        NaN   840000.0
3   Neha  28.00         5.0  42000.0         IT  Bangalore        NaN
4  Arjun  24.25         4.0  65000.0         IT  Bangalore  1300000.0
5  Pooja  23.00         NaN  32000.0         HR        NaN   640000.0

In [23]:
df.drop_duplicates()
df

    Name    Age  Experience   Salary Department       City    new sal
0   Aman  22.00         1.0  30000.0         IT      Delhi   600000.0
1   Riya  24.25         3.0  50000.0         HR     Mumbai  1000000.0
2  Kunal  24.00         NaN  42000.0         IT        NaN   840000.0
3   Neha  28.00         5.0  42000.0         IT  Bangalore        NaN
4  Arjun  24.25         4.0  65000.0         IT  Bangalore  1300000.0
5  Pooja  23.00         NaN  32000.0         HR        NaN   640000.0

In [25]:
df["City"].fillna(df["City"].mode()[0],inplace=True)
df

    Name    Age  Experience   Salary Department       City    new sal
0   Aman  22.00         1.0  30000.0         IT      Delhi   600000.0
1   Riya  24.25         3.0  50000.0         HR     Mumbai  1000000.0
2  Kunal  24.00         NaN  42000.0         IT  Bangalore   840000.0
3   Neha  28.00         5.0  42000.0         IT  Bangalore        NaN
4  Arjun  24.25         4.0  65000.0         IT  Bangalore  1300000.0
5  Pooja  23.00         NaN  32000.0         HR  Bangalore   640000.0

In [28]:
# lambda


df["Salary"]=df["Salary"].apply(lambda x :x/10 if x>50000 else x)
df

    Name    Age  Experience   Salary Department       City    new sal
0   Aman  22.00         1.0  30000.0         IT      Delhi   600000.0
1   Riya  24.25         3.0  50000.0         HR     Mumbai  1000000.0
2  Kunal  24.00         NaN  42000.0         IT  Bangalore   840000.0
3   Neha  28.00         5.0  42000.0         IT  Bangalore        NaN
4  Arjun  24.25         4.0   6500.0         IT  Bangalore  1300000.0
5  Pooja  23.00         NaN  32000.0         HR  Bangalore   640000.0