In [2]:
import pandas as pd
import numpy as np

In [5]:
a=np.arange(0,20).reshape(5,4)

In [8]:
# creating data frame
# first is data,second val is index names for rows then columns
df=pd.DataFrame(a,index=["row1","row2","row3","row4","row5"],columns=["col1","col2","col3","col4"])
df

      col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19

In [9]:
# using row index name using loc
df.loc[['row3','row4']]

      col1  col2  col3  col4
row3     8     9    10    11
row4    12    13    14    15

In [ ]:
# accesng both using iloc ->index locaatio   
# row,index form

# index starts from 0 in both row and columns
df.iloc[2:4,0:2]

      col1  col2
row3     8     9
row4    12    13

In [14]:
# if only start index given then from that index till end

df.iloc[2:,1:]

      col2  col3  col4
row3     9    10    11
row4    13    14    15
row5    17    18    19

In [16]:
df.iloc[:,0]

row1     0
row2     4
row3     8
row4    12
row5    16
Name: col1, dtype: int64

In [17]:
df.iloc[:,3]

row1     3
row2     7
row3    11
row4    15
row5    19
Name: col4, dtype: int64

In [19]:
# combining in one
# : ->means all rows

df.iloc[:,[0,3]]

      col1  col4
row1     0     3
row2     4     7
row3     8    11
row4    12    15
row5    16    19

In [20]:
df['col3'].value_counts()

col3
2     1
6     1
10    1
14    1
18    1
Name: count, dtype: int64

In [21]:
df['col1'].unique()

array([ 0,  4,  8, 12, 16])

In [22]:
df>2

       col1   col2   col3  col4
row1  False  False  False  True
row2   True   True   True  True
row3   True   True   True  True
row4   True   True   True  True
row5   True   True   True  True

In [23]:
df['col1']>2

row1    False
row2     True
row3     True
row4     True
row5     True
Name: col1, dtype: bool